export interface accesoI{
  ID?: any;
  ID_INFANTE: any;
  ID_EMPRESA: any;
  BND_ENTRADA:any;
  BND_SALIDA:any;
  DES_OBSERVACIONES:any;
  FECHA?: any;
  URL_FOTO_SALIDA: any;
  URL_FOTO_ENTRADA: any;
  URL_FOTO_FIRMA_TUTOR_ENTRADA:any;
  URL_FOTO_FIRMA_TUTOR_SALIDA:any;
  URL_FOTO_FIRMA_NINERA_ENTRADA:any;
  URL_FOTO_FIRMA_NINERA_SALIDA:any;
  BND_ENFERMO:any;
  DES_MEDICAMENTO:any;
  BND_LIMPIO_ENTRADA:any;
  BND_LIMPIO_SALIDA:any;
  BND_MOCHILA_COMPLETA_ENTRADA:any;
  DES_ESTADO_FICIO:any;
  DES_NOMBRE_ASISTENTE:any;
  BND_MOCHILA_COMPLETA_SALIDA:any;
  BND_BUEN_ESTADO_FISICO:any;
  DES_OBSERVACIONES_SALIDA:any;
  ID_QR_ENTRADA:any;
  ID_QR_SALIDA:any;
  DES_NOMBRE:any;
  DES_APELLIDO_PATERNO:any;
  DES_APELLIDO_MATERNO:any;
  FECHA_ENTRADA:any;
  DES_ENFERMO:any;
  DES_ESTADO_FISICO_ENTRADA:any;
  BND_ESTADO_FISICO:any;

}
export interface accesoFotoI{
  ID?: any;
  URL_FOTO_SALIDA: any;

}
export interface actualizarI{
  ID_INFANTE: any;
  BND_ENFERMO:any;
  DES_MEDICAMENTO:any;
  BND_LIMPIO_ENTRADA:any;
  BND_MOCHILA_COMPLETA_ENTRADA:any;
  DES_OBSERVACIONES:any;
}

export interface observacionesI{
  ID_INFANTE: any;
  DES_OBSERVACIONES: any;

}

