
export interface estanciaI {

    ID?:any,
    ID_INFANTE:'ID_INFANTE',
    ID_EMPRESA:'ID_EMPRESA',
    DES_DESAYUNO:'DES_DESAYUNO',
    DES_COLACION:'DES_COLACION',
    DES_COMIDA:'DES_COMIDA',
    DES_OBSERVACIONES_ALIMENTACION:'DES_OBSERVACIONES_ALIMENTACION',
    BND_DURMIO:'BND_DURMIO',
    NUM_TIEMPO_SIESTA:'NUM_TIEMPO_SIESTA',
    DES_COMENTARIOS_SIESTA:'DES_COMENTARIOS_SIESTA',
    DES_CONTROL_ESFINTERES:'DES_CONTROL_ESFINTERES',
    BND_AVISO_CONTROL_ESFINTERES:'BND_AVISO_CONTROL_ESFINTERES',
    NUM_VECES_PIPI:'NUM_VECES_PIPI',
    NUM_VECES_POPO:'NUM_VECES_POPO',
    NUM_VECES_AVISO_PIPI:'NUM_VECES_AVISO_PIPI',
    NUM_VECES_AVISO_POPO:'NUM_VECES_AVISO_POPO',
    DES_OBSERVACIONES_FUNCIONES_EXCRETORAS:'DES_OBSERVACIONES_FUNCIONES_EXCRETORAS',
    DES_ESTADO_ANIMO:'DES_ESTADO_ANIMO',
    BND_LLORO:'BND_LLORO',
    BND_PELEO:'BND_PELEO',
    BND_PARTICIPO:'BND_PARTICIPO',
    DES_OBSERVACIONES_ESTADO_ANIMO:'DES_OBSERVACIONES_ESTADO_ANIMO',
    BND_ACCIDENTE:'BND_ACCIDENTE',
    DES_ACCIDENTE:'DES_ACCIDENTE',
    DES_FOLIO_REPORTE_ACCIDENTES:'DES_FOLIO_REPORTE_ACCIDENTES',
    BND_PROBLEMA_SALUD:'BND_PROBLEMA_SALUD',
    DES_PROBLEMA_SALUD:'DES_PROBLEMA_SALUD',
    DES_ATENCION_PROPORCIONADA:'DES_ATENCION_PROPORCIONADA',
    DES_OBSERVACIONES_GENERALES:'DES_OBSERVACIONES_GENERALES',
    FECHA :'FECHA'


}
